//
// File generated by /afs/naf.desy.de/products/root/amd64_rhel50/5.30.00/bin/rootcint at Tue May 22 10:01:51 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdISFrameTools_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SFrameTools_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::FJet FJet;
      #else
      class FJet  {
         public:
         //friend XX;
         #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
         typedef ::FJet::EStrategy EStrategy;
         #else
         enum EStrategy  {
         };
         #endif

         #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
         typedef ::FJet::EAreaType EAreaType;
         #else
         enum EAreaType  {
         };
         #endif

         ::fastjet::ClusterSequence* fJetFinder; //! new object every time fastjet is called
         ::fastjet::JetAlgorithm fJetAlgo; //! the required jet algorithm
         ::fastjet::RecombinationScheme fRecombScheme; //! the required recombination scheme
         ::fastjet::Strategy fStrategy; //! the strategy FastJet uses
         double fR; //! jet finder radius
         double fPtMin; //! Pt_min of clustered jets
         ::fastjet::JetDefinition* fJetDef; //! the jet definition 
         vector< int > fpart_jet_assoc; //! indices of jet constituents
         bool bUseArea; //! calculate area? (default: false)
         ::fastjet::AreaDefinition* fAreaDef; //! area definition
         ::fastjet::GhostedAreaSpec* fGhostSpec; //! ghosted area specifications
         ::fastjet::VoronoiAreaSpec* fVoronoiSpec; //! voronoi area specifications
         ::fastjet::AreaType fGhostAreaType; //! the requested area type
         bool bVoronoiArea; //! calculate voronoi area? (default: false)
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void FJet_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void FJet_Dictionary();
   static void *new_FJet(void *p = 0);
   static void *newArray_FJet(Long_t size, void *p);
   static void delete_FJet(void *p);
   static void deleteArray_FJet(void *p);
   static void destruct_FJet(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::FJet*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::FJet) == sizeof(::ROOT::Shadow::FJet));
      ::FJet *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::FJet),0);
      static ::ROOT::TGenericClassInfo 
         instance("FJet", "./include/FJet.h", 14,
                  typeid(::FJet), DefineBehavior(ptr, ptr),
                  &FJet_ShowMembers, &FJet_Dictionary, isa_proxy, 4,
                  sizeof(::FJet) );
      instance.SetNew(&new_FJet);
      instance.SetNewArray(&newArray_FJet);
      instance.SetDelete(&delete_FJet);
      instance.SetDeleteArray(&deleteArray_FJet);
      instance.SetDestructor(&destruct_FJet);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::FJet*)
   {
      return GenerateInitInstanceLocal((::FJet*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::FJet*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void FJet_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::FJet*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void FJet_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class FJet.
      typedef ::ROOT::Shadow::FJet ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::FJet*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fJetFinder", &sobj->fJetFinder);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fJetAlgo", &sobj->fJetAlgo);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRecombScheme", &sobj->fRecombScheme);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fStrategy", &sobj->fStrategy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fR", &sobj->fR);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPtMin", &sobj->fPtMin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fJetDef", &sobj->fJetDef);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fpart_jet_assoc", (void*)&sobj->fpart_jet_assoc);
      R__insp.InspectMember("vector<int>", (void*)&sobj->fpart_jet_assoc, "fpart_jet_assoc.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bUseArea", &sobj->bUseArea);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fAreaDef", &sobj->fAreaDef);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGhostSpec", &sobj->fGhostSpec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVoronoiSpec", &sobj->fVoronoiSpec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fGhostAreaType", &sobj->fGhostAreaType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bVoronoiArea", &sobj->bVoronoiArea);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_FJet(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::FJet : new ::FJet;
   }
   static void *newArray_FJet(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::FJet[nElements] : new ::FJet[nElements];
   }
   // Wrapper around operator delete
   static void delete_FJet(void *p) {
      delete ((::FJet*)p);
   }
   static void deleteArray_FJet(void *p) {
      delete [] ((::FJet*)p);
   }
   static void destruct_FJet(void *p) {
      typedef ::FJet current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::FJet

/********************************************************
* src/SFrameTools_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSFrameTools_Dict();

extern "C" void G__set_cpp_environmentSFrameTools_Dict() {
  G__cpp_reset_tagtableSFrameTools_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevSFrameTools_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* FJet */
static int G__SFrameTools_Dict_669_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FJet* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FJet[n];
     } else {
       p = new((void*) gvp) FJet[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FJet;
     } else {
       p = new((void*) gvp) FJet;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJet));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->FindJets(*((const vector<Particle*>*) G__int(libp->para[0])), *(vector<Jet*>*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->PrepareInput(*((vector<GenParticle>*) G__int(libp->para[0])), *(vector<Particle*>*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<int>* pobj;
         vector<int> xobj = ((FJet*) G__getstructoffset())->GetPartJetAssoc();
         pobj = new vector<int>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->Init();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->Print((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetJetAlgorithm((fastjet::JetAlgorithm) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetRecombScheme((fastjet::RecombinationScheme) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetRadius((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetPtCut((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((FJet*) G__getstructoffset())->CalculateArea((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((FJet*) G__getstructoffset())->CalculateArea();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->InitArea();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetAreaType((FJet::EAreaType) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetGhostMaxRap((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetGhostRepeat((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetGhostArea((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetGhostGridScatter((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetGhostKtScatter((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetGhostMeanKt((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FJet*) G__getstructoffset())->SetVoronoiEffR((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((FJet*) G__getstructoffset())->GetJetAlgorithm());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((FJet*) G__getstructoffset())->GetRecombScheme());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((FJet*) G__getstructoffset())->GetExclusiveDmerge((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((FJet*) G__getstructoffset())->GetRadius());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SFrameTools_Dict_669_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((FJet*) G__getstructoffset())->GetPtCut());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__SFrameTools_Dict_669_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   FJet* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new FJet(*(FJet*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJet));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef FJet G__TFJet;
static int G__SFrameTools_Dict_669_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (FJet*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((FJet*) (soff+(sizeof(FJet)*i)))->~G__TFJet();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (FJet*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((FJet*) (soff))->~G__TFJet();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__SFrameTools_Dict_669_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FJet* dest = (FJet*) G__getstructoffset();
   *dest = *(FJet*) libp->para[0].ref;
   const FJet& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* FJet */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSFrameTools_Dict {
 public:
  G__Sizep2memfuncSFrameTools_Dict(): p(&G__Sizep2memfuncSFrameTools_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSFrameTools_Dict::*p)();
};

size_t G__get_sizep2memfuncSFrameTools_Dict()
{
  G__Sizep2memfuncSFrameTools_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSFrameTools_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSFrameTools_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Particle>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEParticlecOallocatorlEParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEParticlecOallocatorlEParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEParticlecOallocatorlEParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<GenParticle>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEGenParticlecOallocatorlEGenParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEGenParticlecOallocatorlEGenParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEGenParticlecOallocatorlEGenParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEGenParticlecOallocatorlEGenParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEGenParticlecOallocatorlEGenParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PseudoJet>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<fastjet::PseudoJet>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<std::string,unsigned int>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_pairlEstringcOunsignedsPintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<Summary>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_listlEpairlEstringcOunsignedsPintgRcOallocatorlEpairlEstringcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<pair<string,unsigned int> >",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_listlEpairlEstringcOunsignedsPintgRcOallocatorlEpairlEstringcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<const PseudoJet*>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<const fastjet::PseudoJet*>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<EtaPhi>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<fastjet::EtaPhi>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<history_element>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<fastjet::ClusterSequence::history_element>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<const history_element*>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_setlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUcOlesslEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRcOallocatorlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<const fastjet::ClusterSequence::history_element*>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_setlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUcOlesslEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRcOallocatorlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<const fastjet::ClusterSequence::history_element*,less<const fastjet::ClusterSequence::history_element*> >",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_setlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUcOlesslEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRcOallocatorlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<double,TwoVertices>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_multimaplEdoublecOpairlEintcOintgRcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOpairlEintcOintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<double,pair<int,int> >",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_multimaplEdoublecOpairlEintcOintgRcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOpairlEintcOintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<double,pair<int,int>,less<double> >",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_multimaplEdoublecOpairlEintcOintgRcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOpairlEintcOintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Tile>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<fastjet::ClusterSequence::Tile>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ClusterSequence::history_element>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<GhostJet>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<fastjet::ClusterSequenceActiveArea::GhostJet>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Particle*>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEParticlemUcOallocatorlEParticlemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlemUcOallocatorlEParticlemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEParticlemUcOallocatorlEParticlemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlemUcOallocatorlEParticlemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEParticlemUcOallocatorlEParticlemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Jet*>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEJetmUcOallocatorlEJetmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEJetmUcOallocatorlEJetmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEJetmUcOallocatorlEJetmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEJetmUcOallocatorlEJetmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEJetmUcOallocatorlEJetmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* FJet */
static void G__setup_memvarFJet(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SFrameTools_DictLN_FJet));
   { FJet *p; p=(FJet*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEStrategy),-1,-2,1,G__FastAllocString(2048).Format("eN2Plain=%lldLL",(long long)FJet::eN2Plain).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEStrategy),-1,-2,1,G__FastAllocString(2048).Format("eN2Tiled=%lldLL",(long long)FJet::eN2Tiled).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEStrategy),-1,-2,1,G__FastAllocString(2048).Format("eN2MinHeapTiled=%lldLL",(long long)FJet::eN2MinHeapTiled).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEStrategy),-1,-2,1,G__FastAllocString(2048).Format("eNlnN=%lldLL",(long long)FJet::eNlnN).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEStrategy),-1,-2,1,G__FastAllocString(2048).Format("eNlnNCam=%lldLL",(long long)FJet::eNlnNCam).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEStrategy),-1,-2,1,G__FastAllocString(2048).Format("eBest=%lldLL",(long long)FJet::eBest).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEAreaType),-1,-2,1,G__FastAllocString(2048).Format("eActive=%lldLL",(long long)FJet::eActive).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEAreaType),-1,-2,1,G__FastAllocString(2048).Format("eActiveGhostsInJets=%lldLL",(long long)FJet::eActiveGhostsInJets).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEAreaType),-1,-2,1,G__FastAllocString(2048).Format("ePassiveOneGhost=%lldLL",(long long)FJet::ePassiveOneGhost).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEAreaType),-1,-2,1,G__FastAllocString(2048).Format("ePassive=%lldLL",(long long)FJet::ePassive).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__SFrameTools_DictLN_FJetcLcLEAreaType),-1,-2,1,G__FastAllocString(2048).Format("eVoronoi=%lldLL",(long long)FJet::eVoronoi).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLClusterSequence),-1,-1,4,"fJetFinder=",0,"! new object every time fastjet is called");
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLJetAlgorithm),-1,-1,4,"fJetAlgo=",0,"! the required jet algorithm");
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLRecombinationScheme),-1,-1,4,"fRecombScheme=",0,"! the required recombination scheme");
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLStrategy),-1,-1,4,"fStrategy=",0,"! the strategy FastJet uses");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fR=",0,"! jet finder radius");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fPtMin=",0,"! Pt_min of clustered jets");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLJetDefinition),-1,-1,4,"fJetDef=",0,"! the jet definition ");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"fpart_jet_assoc=",0,"! indices of jet constituents");
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"bUseArea=",0,"! calculate area? (default: false)");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLAreaDefinition),-1,-1,4,"fAreaDef=",0,"! area definition");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLGhostedAreaSpec),-1,-1,4,"fGhostSpec=",0,"! ghosted area specifications");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLVoronoiAreaSpec),-1,-1,4,"fVoronoiSpec=",0,"! voronoi area specifications");
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLAreaType),-1,-1,4,"fGhostAreaType=",0,"! the requested area type");
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"bVoronoiArea=",0,"! calculate voronoi area? (default: false)");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSFrameTools_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncFJet(void) {
   /* FJet */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SFrameTools_DictLN_FJet));
   G__memfunc_setup("FJet",361,G__SFrameTools_Dict_669_0_1, 105, G__get_linked_tagnum(&G__SFrameTools_DictLN_FJet), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindJets",791,G__SFrameTools_Dict_669_0_2, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<Particle*,allocator<Particle*> >' 'vector<Particle*>' 10 - parts u 'vector<Jet*,allocator<Jet*> >' 'vector<Jet*>' 1 - jets", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrepareInput",1247,G__SFrameTools_Dict_669_0_3, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<GenParticle,allocator<GenParticle> >' 'vector<GenParticle>' 0 - genparts u 'vector<Particle*,allocator<Particle*> >' 'vector<Particle*>' 1 - out", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPartJetAssoc",1491,G__SFrameTools_Dict_669_0_4, 117, G__get_linked_tagnum(&G__SFrameTools_DictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,G__SFrameTools_Dict_669_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__SFrameTools_Dict_669_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - usertitle", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetJetAlgorithm",1526,G__SFrameTools_Dict_669_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i 'fastjet::JetAlgorithm' - 0 - algo", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRecombScheme",1497,G__SFrameTools_Dict_669_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i 'fastjet::RecombinationScheme' - 0 - recom", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRadius",916,G__SFrameTools_Dict_669_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - radius", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPtCut",796,G__SFrameTools_Dict_669_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - ptmin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateArea",1287,G__SFrameTools_Dict_669_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitArea",781,G__SFrameTools_Dict_669_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAreaType",1095,G__SFrameTools_Dict_669_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "i 'FJet::EAreaType' - 0 - type", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGhostMaxRap",1402,G__SFrameTools_Dict_669_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - max_rap", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGhostRepeat",1426,G__SFrameTools_Dict_669_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - repeat", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGhostArea",1194,G__SFrameTools_Dict_669_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - area", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGhostGridScatter",1933,G__SFrameTools_Dict_669_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - scatter", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGhostKtScatter",1734,G__SFrameTools_Dict_669_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - scatter", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGhostMeanKt",1393,G__SFrameTools_Dict_669_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - meankt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetVoronoiEffR",1403,G__SFrameTools_Dict_669_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - factor", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetJetAlgorithm",1514,G__SFrameTools_Dict_669_0_21, 105, G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLJetAlgorithm), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRecombScheme",1485,G__SFrameTools_Dict_669_0_22, 105, G__get_linked_tagnum(&G__SFrameTools_DictLN_fastjetcLcLRecombinationScheme), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetExclusiveDmerge",1836,G__SFrameTools_Dict_669_0_23, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - Njet", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRadius",904,G__SFrameTools_Dict_669_0_24, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPtCut",784,G__SFrameTools_Dict_669_0_25, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("FJet", 361, G__SFrameTools_Dict_669_0_26, (int) ('i'), G__get_linked_tagnum(&G__SFrameTools_DictLN_FJet), -1, 0, 1, 1, 1, 0, "u 'FJet' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~FJet", 487, G__SFrameTools_Dict_669_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__SFrameTools_Dict_669_0_28, (int) ('u'), G__get_linked_tagnum(&G__SFrameTools_DictLN_FJet), -1, 1, 1, 1, 1, 0, "u 'FJet' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSFrameTools_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSFrameTools_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSFrameTools_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SFrameTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEParticlecOallocatorlEParticlegRsPgR = { "vector<Particle,allocator<Particle> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Particle,allocator<Particle> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEGenParticlecOallocatorlEGenParticlegRsPgR = { "vector<GenParticle,allocator<GenParticle> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEGenParticlecOallocatorlEGenParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<GenParticle,allocator<GenParticle> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjet = { "fastjet" , 110 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjetcLcLClusterSequence = { "fastjet::ClusterSequence" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgR = { "vector<fastjet::PseudoJet,allocator<fastjet::PseudoJet> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<fastjet::PseudoJet,allocator<fastjet::PseudoJet> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjetcLcLStrategy = { "fastjet::Strategy" , 101 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjetcLcLJetAlgorithm = { "fastjet::JetAlgorithm" , 101 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjetcLcLRecombinationScheme = { "fastjet::RecombinationScheme" , 101 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjetcLcLJetDefinition = { "fastjet::JetDefinition" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_pairlEstringcOunsignedsPintgR = { "pair<string,unsigned int>" , 115 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_listlEpairlEstringcOunsignedsPintgRcOallocatorlEpairlEstringcOunsignedsPintgRsPgRsPgR = { "list<pair<string,unsigned int>,allocator<pair<string,unsigned int> > >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgR = { "vector<const fastjet::PseudoJet*,allocator<const fastjet::PseudoJet*> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<const fastjet::PseudoJet*,allocator<const fastjet::PseudoJet*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjetcLcLGhostedAreaSpec = { "fastjet::GhostedAreaSpec" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjetcLcLVoronoiAreaSpec = { "fastjet::VoronoiAreaSpec" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjetcLcLAreaType = { "fastjet::AreaType" , 101 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_fastjetcLcLAreaDefinition = { "fastjet::AreaDefinition" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgR = { "vector<fastjet::EtaPhi,allocator<fastjet::EtaPhi> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgRcLcLiteratorgR = { "reverse_iterator<vector<fastjet::EtaPhi,allocator<fastjet::EtaPhi> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgR = { "vector<fastjet::ClusterSequence::history_element,allocator<fastjet::ClusterSequence::history_element> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<fastjet::ClusterSequence::history_element,allocator<fastjet::ClusterSequence::history_element> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_setlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUcOlesslEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRcOallocatorlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRsPgR = { "set<const fastjet::ClusterSequence::history_element*,less<const fastjet::ClusterSequence::history_element*>,allocator<const fastjet::ClusterSequence::history_element*> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_multimaplEdoublecOpairlEintcOintgRcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOpairlEintcOintgRsPgRsPgRsPgR = { "multimap<double,pair<int,int>,less<double>,allocator<pair<const double,pair<int,int> > > >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgR = { "vector<fastjet::ClusterSequence::Tile,allocator<fastjet::ClusterSequence::Tile> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<fastjet::ClusterSequence::Tile,allocator<fastjet::ClusterSequence::Tile> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgR = { "vector<fastjet::ClusterSequenceActiveArea::GhostJet,allocator<fastjet::ClusterSequenceActiveArea::GhostJet> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<fastjet::ClusterSequenceActiveArea::GhostJet,allocator<fastjet::ClusterSequenceActiveArea::GhostJet> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_FJet = { "FJet" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_FJetcLcLEStrategy = { "FJet::EStrategy" , 101 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_FJetcLcLEAreaType = { "FJet::EAreaType" , 101 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEParticlemUcOallocatorlEParticlemUgRsPgR = { "vector<Particle*,allocator<Particle*> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlemUcOallocatorlEParticlemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Particle*,allocator<Particle*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_vectorlEJetmUcOallocatorlEJetmUgRsPgR = { "vector<Jet*,allocator<Jet*> >" , 99 , -1 };
G__linked_taginfo G__SFrameTools_DictLN_reverse_iteratorlEvectorlEJetmUcOallocatorlEJetmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Jet*,allocator<Jet*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSFrameTools_Dict() {
  G__SFrameTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEParticlecOallocatorlEParticlegRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEGenParticlecOallocatorlEGenParticlegRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEGenParticlecOallocatorlEGenParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjet.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjetcLcLClusterSequence.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjetcLcLStrategy.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjetcLcLJetAlgorithm.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjetcLcLRecombinationScheme.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjetcLcLJetDefinition.tagnum = -1 ;
  G__SFrameTools_DictLN_pairlEstringcOunsignedsPintgR.tagnum = -1 ;
  G__SFrameTools_DictLN_listlEpairlEstringcOunsignedsPintgRcOallocatorlEpairlEstringcOunsignedsPintgRsPgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjetcLcLGhostedAreaSpec.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjetcLcLVoronoiAreaSpec.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjetcLcLAreaType.tagnum = -1 ;
  G__SFrameTools_DictLN_fastjetcLcLAreaDefinition.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_setlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUcOlesslEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRcOallocatorlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_multimaplEdoublecOpairlEintcOintgRcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOpairlEintcOintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_FJet.tagnum = -1 ;
  G__SFrameTools_DictLN_FJetcLcLEStrategy.tagnum = -1 ;
  G__SFrameTools_DictLN_FJetcLcLEAreaType.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEParticlemUcOallocatorlEParticlemUgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlemUcOallocatorlEParticlemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SFrameTools_DictLN_vectorlEJetmUcOallocatorlEJetmUgRsPgR.tagnum = -1 ;
  G__SFrameTools_DictLN_reverse_iteratorlEvectorlEJetmUcOallocatorlEJetmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSFrameTools_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEParticlecOallocatorlEParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEGenParticlecOallocatorlEGenParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEGenParticlecOallocatorlEGenParticlegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjet);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjetcLcLClusterSequence);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLPseudoJetcOallocatorlEfastjetcLcLPseudoJetgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjetcLcLStrategy);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjetcLcLJetAlgorithm);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjetcLcLRecombinationScheme);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjetcLcLJetDefinition);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_pairlEstringcOunsignedsPintgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_listlEpairlEstringcOunsignedsPintgRcOallocatorlEpairlEstringcOunsignedsPintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEconstsPfastjetcLcLPseudoJetmUcOallocatorlEconstsPfastjetcLcLPseudoJetmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjetcLcLGhostedAreaSpec);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjetcLcLVoronoiAreaSpec);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjetcLcLAreaType);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_fastjetcLcLAreaDefinition);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLEtaPhicOallocatorlEfastjetcLcLEtaPhigRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLhistory_elementcOallocatorlEfastjetcLcLClusterSequencecLcLhistory_elementgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_setlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUcOlesslEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRcOallocatorlEconstsPfastjetcLcLClusterSequencecLcLhistory_elementmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_multimaplEdoublecOpairlEintcOintgRcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOpairlEintcOintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequencecLcLTilecOallocatorlEfastjetcLcLClusterSequencecLcLTilegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetcOallocatorlEfastjetcLcLClusterSequenceActiveAreacLcLGhostJetgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_FJet),sizeof(FJet),-1,263424,(char*)NULL,G__setup_memvarFJet,G__setup_memfuncFJet);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_FJetcLcLEStrategy);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_FJetcLcLEAreaType);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEParticlemUcOallocatorlEParticlemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEParticlemUcOallocatorlEParticlemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_vectorlEJetmUcOallocatorlEJetmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SFrameTools_DictLN_reverse_iteratorlEvectorlEJetmUcOallocatorlEJetmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupSFrameTools_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSFrameTools_Dict()");
  G__set_cpp_environmentSFrameTools_Dict();
  G__cpp_setup_tagtableSFrameTools_Dict();

  G__cpp_setup_inheritanceSFrameTools_Dict();

  G__cpp_setup_typetableSFrameTools_Dict();

  G__cpp_setup_memvarSFrameTools_Dict();

  G__cpp_setup_memfuncSFrameTools_Dict();
  G__cpp_setup_globalSFrameTools_Dict();
  G__cpp_setup_funcSFrameTools_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSFrameTools_Dict();
  return;
}
class G__cpp_setup_initSFrameTools_Dict {
  public:
    G__cpp_setup_initSFrameTools_Dict() { G__add_setup_func("SFrameTools_Dict",(G__incsetup)(&G__cpp_setupSFrameTools_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSFrameTools_Dict() { G__remove_setup_func("SFrameTools_Dict"); }
};
G__cpp_setup_initSFrameTools_Dict G__cpp_setup_initializerSFrameTools_Dict;

